# docker version
version: "3"

services:  
  kc_server:    
    # image: quay.io/keycloak/keycloak:24.0
    image: keycloak/keycloak:24.0.4-0
    # build: .
    container_name: kc_server
    command: start-dev
    volumes:
      # Providers
      # - './providers:/opt/keycloak/providers'
      # Development theme folder
      - './themes/demo/theme:/opt/keycloak/themes'
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: kc_postgres_svr
      KC_DB_URL_DATABASE: keycloak_dev
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak_admin
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      
    ports:      
      - "8085:8080"      
    depends_on:      
      kc_postgres_svr:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"    

  kc_postgres_svr: 
    image: postgres:10
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: keycloak_dev
      POSTGRES_USER: keycloak_admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5431:5432"
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"

  kc_adminer:
    image: adminer:latest
    container_name: kc_adminer
    environment:
      ADMINER_DEFAULT_SERVER: kc_postgres_svr
    ports:
      - 8885:8080
    networks:
      network_sso:
        ipv4_address: "10.0.0.4"

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=users
        - LDAP_DOMAIN=workstationcrm.au
        - "LDAP_BASE_DN=dc=workstationcrm,dc=au"
        - LDAP_ADMIN_PASSWORD=password
    ports:
        - 389:389
        - 636:636
    networks:
      network_sso:
        ipv4_address: "10.0.0.5"

networks:  
  network_sso:
    ipam:
    # IP Address management
      driver: default
      # default = bridge
      config:
        - subnet: "10.0.0.0/24"